// Multilingual resources (French, Arabic, Tamazight in Tifinagh)
// Inspired by Moroccan reading context

export const TRANSLATIONS = {
  fr: {
    appTitle: "مقرا · Maqra",
    greeting: "Bonjour, Ahmed 👋",
    annualGoal: "Objectif annuel",
    booksRead: "livres lus",
    completed: "complété",
    livres: "Livres",
    pagesLues: "Pages lues",
    ceMois: "Ce mois",
    searchPlaceholder: "Rechercher un livre...",
    myLibrary: "Ma Bibliothèque",
    addBookBtn: "Ajouter un livre 📚",
    title: "Titre",
    author: "Auteur",
    totalPages: "Nombre total de pages",
    language: "Langue",
    status: "Statut",
    cancel: "Annuler",
    add: "Ajouter",
    noBooks: "Aucun livre trouvé",
    
    // Details Screen
    currentProgress: "Progression de lecture",
    currentPage: "Page actuelle",
    update: "Mettre à jour",
    readingSession: "Session de lecture",
    sessionDesc: "Commencez une session de lecture chronométrée pour suivre votre vitesse et votre progression en temps réel.",
    startSession: "Démarrer la session",
    endSession: "Terminer",
    pauseSession: "Pause",
    resumeSession: "Reprendre",
    saveSession: "Enregistrer la session",
    pagesReadQuestion: "Combien de pages avez-vous lues ?",
    sessionCompletedTitle: "Session terminée ! 🎉",
    sessionCompletedMsg: "Vous avez lu pendant {min} min ({time}).",
    emptyDetails: "Aucun livre disponible. Commencez par ajouter un livre dans l'onglet Bibliothèque !",
    markFinished: "Marquer terminé",
    markUnfinished: "Marquer non lu",
    
    // Stats Screen
    globalStats: "Statistiques globales",
    streakActive: "Série active",
    topGenre: "Top genre",
    memberSince: "Membre depuis",
    totalTime: "Temps total",
    chartTitle: "Livres terminés par mois",
    booksTotal: "Livres total",
    streakActiveDays: "{days} jours",
    memberSinceDate: "{date}",
    changeLanguageTitle: "Langue de l'application",
    resetMocksBtn: "Réinitialiser les données",
    location: "Lecteur depuis Casablanca 📍",
    chooseSourceTitle: "Choisir une photo",
    cameraOption: "Prendre une photo 📸",
    galleryOption: "Choisir depuis la galerie 🖼️",
  },
  ar: {
    appTitle: "مقرا · Maqra",
    greeting: "مرحباً، أحمد 👋",
    annualGoal: "الهدف السنوي",
    booksRead: "كتب مقروءة",
    completed: "مكتمل",
    livres: "كتب",
    pagesLues: "صفحات مقروءة",
    ceMois: "هذا الشهر",
    searchPlaceholder: "ابحث عن كتاب...",
    myLibrary: "مكتبتي",
    addBookBtn: "إضافة كتاب 📚",
    title: "العنوان",
    author: "المؤلف",
    totalPages: "عدد الصفحات الإجمالي",
    language: "اللغة",
    status: "الحالة",
    cancel: "إلغاء",
    add: "إضافة",
    noBooks: "لم يتم العثور على كتب",
    
    // Details Screen
    currentProgress: "تقدم القراءة",
    currentPage: "الصفحة الحالية",
    update: "تحديث",
    readingSession: "جلسة قراءة",
    sessionDesc: "ابدأ جلسة قراءة مؤقتة لتتبع سرعتك وتقدمك في الوقت الفعلي.",
    startSession: "بدء الجلسة",
    endSession: "إنهاء",
    pauseSession: "إيقاف مؤقت",
    resumeSession: "استئناف",
    saveSession: "حفظ الجلسة",
    pagesReadQuestion: "كم عدد الصفحات التي قرأتها ؟",
    sessionCompletedTitle: "انتهت الجلسة ! 🎉",
    sessionCompletedMsg: "لقد قرأت لمدة {min} دقيقة ({time}).",
    emptyDetails: "لا توجد كتب متاحة. ابدأ بإضافة كتاب من تبويب المكتبة !",
    markFinished: "تحديد كمكتمل",
    markUnfinished: "تحديد كغير مقروء",
    
    // Stats Screen
    globalStats: "الإحصائيات العامة",
    streakActive: "السلسلة النشطة",
    topGenre: "النوع المفضل",
    memberSince: "عضو منذ",
    totalTime: "الوقت الإجمالي",
    chartTitle: "الكتب المكتملة شهرياً",
    booksTotal: "إجمالي الكتب",
    streakActiveDays: "{days} يوم",
    memberSinceDate: "{date}",
    changeLanguageTitle: "لغة التطبيق",
    resetMocksBtn: "إعادة تعيين البيانات",
    location: "قارئ من الدار البيضاء 📍",
    chooseSourceTitle: "اختر مصدراً",
    cameraOption: "التقاط صورة 📸",
    galleryOption: "اختيار من المعرض 🖼️",
  },
  tz: {
    appTitle: "مقرا · Maqra",
    greeting: "ⴰⵣⵓⵍ, Ahmed 👋",
    annualGoal: "ⵜⵉⵡⵉⵜ ⵜⴰⵙⴳⵯⴰⵏⵜ",
    booksRead: "ⵉⴷⵍⵉⵙⵏ ⵜⵖⵔⵉⴷ",
    completed: "ⵉⴽⵎⵍ",
    livres: "ⵉⴷⵍⵉⵙⵏ",
    pagesLues: "ⵜⵉⴼⵔⵉⵜⵉⵏ ⵜⵖⵔⵉⴷ",
    ceMois: "ⴰⵢⵢⵓⵔ ⴰ",
    searchPlaceholder: "ⵔⵣⵓ ⵙ ⵓⴷⵍⵉⵙ...",
    myLibrary: "ⵜⴰⵙⴷⵍⵉⵙⵜ ⵉⵏⵓ",
    addBookBtn: "ⵔⵏⵓ ⴰⴷⵍⵉⵙ 📚",
    title: "ⵉⵙⵎ",
    author: "ⴰⵎⴰⵔⴰ",
    totalPages: "ⵉⵙⵜⵉⵏ ⵏ ⵜⴼⵔⵉⵜⵉⵏ",
    language: "ⵜⵓⵜⵍⴰⵢⵜ",
    status: "ⵜⴰⴷⴰⴷⵜ",
    cancel: "ⵙⵔⵉⴼ",
    add: "ⵔⵏⵓ",
    noBooks: "ⵓⵔ ⵏⵓⴼⴰ ⴰⵔ ⵓⴷⵍⵉⵙ",
    
    // Details Screen
    currentProgress: "ⵜⴰⴷⴰⴷⵜ ⵏ ⵜⵖⵔⵉ",
    currentPage: "ⵜⴰⴼⵔⵉⵜ ⵜⵓⵔⵉⵍⵜ",
    update: "ⵙⴷⵖⵉ",
    readingSession: "ⵜⵉⵎⵉⵣⴰⵔ ⵏ ⵜⵖⵔⵉ",
    sessionDesc: "ⴱⴷⵓ ⵜⵉⵎⵉⵣⴰⵔ ⵏ ⵜⵖⵔⵉ ⵉⵡⴰⵜⵙ ⵜⴹⴼⴰⵕ ⵜⵉⴼⵔⵉⵜⵉⵏ ⵏⵏⴽ.",
    startSession: "ⴱⴷⵓ ⵜⵉⵎⵉⵣⴰⵔ",
    endSession: "ⴼⵓⴽⴽ",
    pauseSession: "ⵙⵔⵉⴼ ⵢⴰⵜ",
    resumeSession: "ⴱⴷⵓ ⴷⴰⵖ",
    saveSession: "ⵃⴱⵓ ⵜⵉⵎⵉⵣⴰⵔ",
    pagesReadQuestion: "ⵎⵛⵜⴰ ⵏ ⵜⴼⵔⵉⵜⵉⵏ ⵜⵖⵔⵉⴷ ?",
    sessionCompletedTitle: "ⵜⵉⵎⵉⵣⴰⵔ ⵜⴼⵓⴽⴽ ! 🎉",
    sessionCompletedMsg: "ⵜⵖⵔⵉⴷ ⵉ ⵓⴽⵓⴷ ⵏ {min} ⵜⵓⵙⴷⵉⴷⵉⵏ ({time}).",
    emptyDetails: "ⵓⵔ ⵉⵍⵍⵉ ⵓⴷⵍⵉⵙ. ⵔⵏⵓ ⴰⴷⵍⵉⵙ ⴳ ⵜⵙⴷⵍⵉⵙⵜ !",
    markFinished: "ⵉⴽⵎⵍ ⵓⴷⵍⵉⵙ",
    markUnfinished: "ⵓⵔ ⵉⴽⵎⵉⵍ",
    
    // Stats Screen
    globalStats: "ⵜⵉⵙⵏⵉⵎⴰⵍ ⵜⵉⵎⴰⵜⴰⵢⵉⵏ",
    streakActive: "ⵜⴰⵙⵙⵓⵜⵔⴰ ⵜⵓⵔⵉⵍⵜ",
    topGenre: "ⴰⵏⴰⵡ ⵉⵏⵓ",
    memberSince: "ⵎⴻⵎⴱⵔ ⵙⴳ",
    totalTime: "ⴰⴽⵓⴷ ⴰⵎⴰⵜⴰⵢ",
    chartTitle: "ⵉⴷⵍⵉⵙⵏ ⵉⴽⵎⵍⵏ ⵙ ⵓⵢⵢⵓⵔ",
    booksTotal: "ⵉⴷⵍⵉⵙⵏ ⵎⴰⵕⵕⴰ",
    streakActiveDays: "{days} ⵓⵙⵙⴰⵏ",
    memberSinceDate: "{date}",
    changeLanguageTitle: "ⵜⵓⵜⵍⴰⵢⵜ ⵏ ⵓⵙⵏⵙⵓ",
    resetMocksBtn: "ⵙⴷⵖⵉ ⵎⴰⵕⵕⴰ",
    location: "ⴰⵎⵖⵔⵉ ⵙⴳ ⴰⵏⴼⴰ 📍",
    chooseSourceTitle: "ⵙⵜⵉ ⴰⵙⴰⴳⵓⵎ",
    cameraOption: "ⵟⵟⴼ ⵜⴰⵡⵍⴰⴼⵜ 📸",
    galleryOption: "ⵙⵜⵉ ⵙⴳ ⵜⵙⴷⵍⵉⵙⵜ 🖼️",
  }
};
